list: $/rpg/mmorpg/models/planet/columns.yaml
modelClass: Rpg\Mmorpg\Models\Planet
title: Planets
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'rpg/mmorpg/planets/update/:id'
